### ISSUE TITLE
Love it!

### ISSUE THREAD

**Issue by 4lejandrito** [GautierCo/iTongue#2]
Salut! j'aime la façon dont vous utilisez mon projet Creepyface. Cela me rend tellement heureuse!

https://github.com/GautierCo/iTongue/blob/edc7155a3aa799e9f0eaff87a0ac5856ee82524a/client/src/components/Team/RoundAvatar.js#L11-L20

Au fait, j'ai vérifié iTongue et c'est génial!

**Comment by GautierCo** [comment]
Hello ! 
Merci beaucoup Alejandro ! J'ai passé le message à notre équipe, ils sont ravis que cela te plaît !
CreepyFace est génial en tout cas, merci de l'avoir créé !
